name: Zylker-EClassifieds Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write


jobs:
  build:
    name: Creating Zylker-EClassifieds Release
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository
        uses: actions/checkout@v2

      - name: Installing node-18
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Creating release directory
        run: mkdir -p release

      - name: Copying project-template-1.0.0.json
        run: cp project-template-1.0.0.json release/project-template-1.0.0.json

      - name: Generating release
        run: cd release && zip -r release.zip .

      - name: Generating artifacts
        uses: ncipollo/release-action@v1
        with:
          draft: true
          artifacts: "./release/release.zip"
          tag: ${{ env.RELEASE_VERSION }}
